function B = StrainMatrix(L,xi,yi,xj,yj,xm,ym)
%--------------------------------------
% The computation of strain matrix B
%--------------------------------------
ai = xj*ym - xm*yj;
aj = xm*yi - xi*ym;
am = xi*yj - xj*yi;
bi = yj - ym;
bj = ym - yi;
bm = yi - yj;
ci = -(xj-xm);
cj = -(xm-xi);
cm = -(xi-xj);
DoubleAera = abs(ai + aj + am) ;
T   = [bi^2 bj^2 2*bi*bj;
       ci^2 cj^2 2*ci*cj;
       2*bi*ci 2*bj*cj 2*(bi*cj+bj*ci)];
Li  = L(1); Lj = L(2);
Nii = [-4*Lj - 12*Li + 6, ...
       -6*bj*Li + 2*bj - 3*bj*Lj - bm*Lj, ...
       2*cj - 6*cj*Li - 3*cj*Lj - cm*Lj, ...
       -4*Lj, ...
       (-bm + bi)*Lj, ...
       -(cm - ci)*Lj, ...
       -6 + 12*Li + 8*Lj, ...
       bi*Lj - 6*bj*Li + 4*bj - 3*bj*Lj, ...
       ci*Lj + 4*cj - 6*cj*Li - 3*cj*Lj ] ;
Njj = [-4*Li, ...
       -(bj - bm)*Li, ...
       (-cj + cm)*Li, ...
       6 - 4*Li - 12*Lj, ...
       bm*Li + 6*bi*Lj - 2*bi + 3*bi*Li, ...
       cm*Li + 6*ci*Lj - 2*ci + 3*ci*Li, ...
       8*Li - 6 + 12*Lj, ...
       6*bi*Lj - 4*bi + 3*bi*Li - bj*Li, ...
       6*ci*Lj - 4*ci + 3*ci*Li - cj*Li];
Nij = [-4*Li - 4*Lj + 2, ...
       -3*bj*Li - bm*Li + 1/2*bj - bj*Lj - 1/2*bm + bm*Lj, ...
       -3*cj*Li - cm*Li + 1/2*cj - cj*Lj - 1/2*cm + cm*Lj, ...
       -4*Li - 4*Lj + 2, ...
       bm*Lj + 3*bi*Lj + 1/2*bm - bm*Li - 1/2*bi + bi*Li, ...
       cm*Lj + 3*ci*Lj + 1/2*cm - cm*Li - 1/2*ci + ci*Li, ...
       -4 + 8*Li + 8*Lj, ...
       3*bi*Lj - 3/2*bi + bi*Li - 3*bj*Li + 3/2*bj - bj*Lj, ...
       3*ci*Lj - 3/2*ci + ci*Li - 3*cj*Li + 3/2*cj - cj*Lj];
B = -1 / DoubleAera^2 * T * [Nii; Njj; Nij];




