function [ks] = BuildGlobalMatrices(Struct_dof,Elem_num,Elem_Node_num,Node_update,E,t,MU)
ks = zeros(Struct_dof,Struct_dof);
for n     = 1:1:Elem_num
    Ni    = Elem_Node_num(n,1); Nj = Elem_Node_num(n,2);Nm = Elem_Node_num(n,3);
    Localcoord = LocalCoordinate(Node_update(Ni,1), ...
        Node_update(Ni,2),Node_update(Ni,3),Node_update(Nj,1),Node_update(Nj,2), ...
        Node_update(Nj,3),Node_update(Nm,1),Node_update(Nm,2),Node_update(Nm,3));
    ke    = ElasticmatrixTriangleElement(E,MU,t,Localcoord(1,1),Localcoord(2,1), ...
        Localcoord(4,1),Localcoord(5,1),Localcoord(7,1),Localcoord(8,1));
    T     = TransformationmatrixTriangleElement(Node_update(Ni,1), ...
        Node_update(Ni,2),Node_update(Ni,3),Node_update(Nj,1),Node_update(Nj,2), ...
        Node_update(Nj,3),Node_update(Nm,1),Node_update(Nm,2),Node_update(Nm,3));
    K     = T'*ke*T;
    ks    = AssemblyTriangleElement(ks,K,Ni,Nj,Nm);
end